### ISSUE TITLE
Slicing bug CoMList dicomreading.py

### ISSUE THREAD

**Issue by srimeijer** [McGillMedPhys/rtdsm#1]
In dicomreading.py CoMList is initialized as an empty list in row 101. The slicing in the conditional in row 183 is array-like, whereas CoMList is a (nested)list at this point, resulting in a TypeError upon running the examples.

**Comment by haleypats** [comment]
Hello @srimeijer! Thanks so much for bringing this to our attention. I looked into the issue and determined the cause was a failure to convert the nested list to a numpy array before performing the actions at line 183. I have just tested and pushed an updated version of the code that should resolve this issue for you and anyone else. Thank you again for letting us know!
