### ISSUE TITLE
select_intersection_point function

### ISSUE THREAD

**Issue by vickyvignesh10** [McGillMedPhys/rtdsm#3]
![Screenshot 2024-12-24 151423](https://github.com/user-attachments/assets/d21b81d6-d9ae-482d-884f-9241a9870a2d)
Whenever the sample_nonplanar_dsm function is called, the scripts get stuck in the select_intersection_point function in helpers.py module, Kindly resolve this issue

**Comment by jkildea** [comment]
@haleypats Not sure you have time to work on this but thought I should bring it to your attention. Thanks.

**Comment by haleypats** [comment]
Hi @vickyvignesh10, glad you're using rtdsm! I'll do my best to help you troubleshoot with the information you've provided.

First, could you please confirm what data you are using for this (an example from rtdsm or your own), and then if it is your own data, if this is happening with just one of your files or multiple of them. I'm currently operating under the assumption that you're using your own data

Second, could you try running the code again, but this time setting the optional variable "zeroind" to 1 or 2 when running sample_nonplanar_slices instead of its default of 0? If the issue resolves by doing this, that means that cause is likely because your contour is uniquely shaped in a way that is causing the function "find_plane_intersection" to be asked to solve a system of linear equations with infinite solutions, and it then picks an arbitrary solution far outside of the search region used in select_intersection_point. Changing zeroind will change how rtdsm sets up this system of equations and should solve your issue if this is indeed the root cause.

If this does not resolve your issue, could you please run the following modified version of "select_intersection_point" with the specific v, p, and mesh variables that are causing the issue so I can investigate further?

```
#STEP1: set up lambda functions and bounds of the mesh
newT = lambda val,ind: (val - p[ind])/v[ind]    
newP = lambda t : p + v*t           
bounds = mesh.bounds
maxvdim = np.argmax(abs(v)) 
usebounds = bounds[2*maxvdim:2*maxvdim+2]   
print("bounds:",bounds, "maxvdim:",maxvdim,"usebounds:",usebounds
#STEP2: check 10 points within the bounds and see if any fall on the slice (otherwise just give the closest)
closest = (0,10000) #(T, distance)
for i in np.linspace(usebounds[0],usebounds[1],10):
    print("in step ",I," of loop")
    nT = newT(i,maxvdim)
    print("newT and newP are using the values:",nT, newP(nT))
    ppdist = pv.PolyData(newP(nT)).compute_implicit_distance(mesh)
    print("measured distance was:",ppdist)
    if abs(ppdist['implicit_distance'][0])<=closest[1]:
        print("entered the if statement")
        closest = (nT,abs(ppdist['implicit_distance'][0])) 
    point = p+closest[0]*v
print("made it to function end")
```

My suspicion is there's something up with either the v&p values being fed into this function (which would point back to the zeroind adjustment being a possible fix), or there is something wrong with how the slice mesh itself was generated, which could indicate something irregular about the contours in the RT-structure file you're working with. rtdsm is designed to work with planar contours created in common radiotherapy treatment planning software and has been tested on MIM & Eclipse contours. If you are working with RT-structure files created in a different software that do not rest on axial planes, or with contours imported from different file types entirely, you may want to try visualizing how they are being rendered in rtdsm to determine if this could be the cause.

**Comment by vickyvignesh10** [comment]
Thank you for the suggestion sir!, it was indeed the problem with zeroind, which I changed to 1 or 2, based on the system of equations, it instantly resolved the problem. The point p that the find_intersection_plane function calculated was way too off, resulted in infinie looping in the select_intersection_point function. Now the problem is resolved. Thank you so much again
